// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DividerSection: typeof import('./src/components/DividerSection.vue')['default']
    Document: typeof import('./src/components/element/components/Document.vue')['default']
    Edit: typeof import('./src/components/element/components/Edit.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    Eleme: typeof import('./src/components/element/components/Eleme.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Goblet: typeof import('./src/components/element/components/Goblet.vue')['default']
    HelpFilled: typeof import('./src/components/element/components/HelpFilled.vue')['default']
    HomeFilled: typeof import('./src/components/element/components/HomeFilled.vue')['default']
    Key: typeof import('./src/components/element/components/Key.vue')['default']
    LeftMenu: typeof import('./src/components/element/LeftMenu.vue')['default']
    RightNav: typeof import('./src/components/element/RightNav.vue')['default']
    Setting: typeof import('./src/components/element/components/Setting.vue')['default']
    Shop: typeof import('./src/components/element/components/Shop.vue')['default']
    Switch: typeof import('./src/components/element/components/Switch.vue')['default']
    TsxDemo: typeof import('./src/components/testDemo/TsxDemo.vue')['default']
    VetifyClick: typeof import('./src/components/VetifyClick.vue')['default']
    VetifySlide: typeof import('./src/components/VetifySlide.vue')['default']
  }
}

export { }
